development:
  adapter: postgresql
  encoding: unicode
  database: corona_data
  pool: 2
  username: corona_user
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password